In [ ]:
!pip install sdmx1

Collecting sdmx1
  Downloading sdmx1-2.26.0-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: lxml>=3.6 in /usr/local/lib/python3.12/dist-packages (from sdmx1) (6.0.2)
Requirement already satisfied: packaging>=26 in /usr/local/lib/python3.12/dist-packages (from sdmx1) (26.0)
Requirement already satisfied: pandas>=1.0 in /usr/local/lib/python3.12/dist-packages (from sdmx1) (2.2.2)
Requirement already satisfied: platformdirs>=4.1 in /usr/local/lib/python3.12/dist-packages (from sdmx1) (4.9.4)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.12/dist-packages (from sdmx1) (2.9.0.post0)
Requirement already satisfied: requests>=2.7 in /usr/local/lib/python3.12/dist-packages (from sdmx1) (2.32.4)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0->sdmx1) (2.0.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0->sdmx1) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0->sdmx1) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil->sdmx1) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.7->sdmx1) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.7->sdmx1) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.7->sdmx1) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.7->sdmx1) (2026.2.25)
Downloading sdmx1-2.26.0-py3-none-any.whl (267 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 267.5/267.5 kB 6.9 MB/s eta 0:00:00
Installing collected packages: sdmx1
Successfully installed sdmx1-2.26.0

In [ ]:
import sdmx

IMF_DATA = sdmx.Client('IMF_DATA')

data_msg = IMF_DATA.data('FM', key='VNM.G2M_S13_POGDP_PT.A', params={'startPeriod': 2018, 'endPeriod': 2022})

df = sdmx.to_pandas(data_msg)

df

WARNING:sdmx.reader.xml.v21:xml.Reader got no structure=… argument for StructureSpecificData

TIME_PERIOD  INDICATOR         COUNTRY  FREQUENCY  OVERLAP  SCALE  METHODOLOGY
2018         G2M_S13_POGDP_PT  VNM      A          OL       0      GFS            20.479760
2019         G2M_S13_POGDP_PT  VNM      A          OL       0      GFS            19.811254
2020         G2M_S13_POGDP_PT  VNM      A          OL       0      GFS            21.251144
2021         G2M_S13_POGDP_PT  VNM      A          OL       0      GFS            20.124806
2022         G2M_S13_POGDP_PT  VNM      A          OL       0      GFS            18.196885
Name: value, dtype: float64

In [ ]:
df.index = df.index.get_level_values('TIME_PERIOD')
df

TIME_PERIOD
2018    20.479760
2019    19.811254
2020    21.251144
2021    20.124806
2022    18.196885
Name: value, dtype: float64