In [2]:
from vnstock import register_user
register_user(api_key='vnstock_d01d9dad451a277e8430ac854a48159e')

✓ API key đã được lưu thành công! (API key saved successfully!)
Bạn đang sử dụng Phiên bản cộng đồng (60 requests/phút)
(You are using Community version - 60 requests/minute)

Để tham gia gói thành viên tài trợ (To join sponsor membership):
  Truy cập: https://vnstocks.com/insiders-program
✓ API key đã được lưu thành công! vnst***159e
✓ Bạn đang sử dụng Phiên bản cộng đồng (60 requests/phút)

True

In [8]:
from vnstock import Listing
listing = Listing(source='VCI')
list=listing.symbols_by_industries()
list

,symbol,organ_name,icb_name3,icb_name2,icb_name4,com_type_code,icb_code1,icb_code2,icb_code3,icb_code4
0,BQP,Công ty Cổ phần Nhựa chất lượng cao Bình Thuận,Hóa chất,Hóa chất,"Nhựa, cao su & sợi",CT,1000,1300,1350,1353
1,VLS,Công ty Cổ phần Sản xuất Thép Việt Long,Kim loại,Tài nguyên Cơ bản,Thép và sản phẩm thép,CT,1000,1700,1750,1757
2,RYG,Công ty Cổ phần Sản xuất và Đầu tư Hoàng Gia,Xây dựng và Vật liệu,Xây dựng và Vật liệu,Vật liệu xây dựng & Nội thất,CT,2000,2300,2350,2353
3,F88,Công ty Cổ phần Đầu tư F88,Dịch vụ tài chính,Dịch vụ tài chính,Tài chính cá nhân,CT,8000,8700,8770,8773
4,DVT,Công ty Cổ phần Đào tạo và Dịch vụ Giao thông ...,Tư vấn & Hỗ trợ Kinh doanh,Hàng & Dịch vụ Công nghiệp,Đào tạo & Việc làm,CT,2000,2700,2790,2793
...,...,...,...,...,...,...,...,...,...,...
1543,TIS,Công ty Cổ phần Gang thép Thái Nguyên,Kim loại,Tài nguyên Cơ bản,Thép và sản phẩm thép,CT,1000,1700,1750,1757
1544,VPC,Công ty Cổ phần Đầu tư và Phát triển Năng lượn...,Xây dựng và Vật liệu,Xây dựng và Vật liệu,Xây dựng,CT,2000,2300,2350,2357
1545,VTQ,Công ty Cổ phần Việt Trung Quảng Bình,Hóa chất,Hóa chất,"Nhựa, cao su & sợi",CT,1000,1300,1350,1353
1546,TVM,Công ty Cổ phần Tư vấn đầu tư Mỏ và công nghiệ...,Tư vấn & Hỗ trợ Kinh doanh,Hàng & Dịch vụ Công nghiệp,Tư vấn & Hỗ trợ KD,CT,2000,2700,2790,2791
1547,VIN,Công ty Cổ phần Giao nhận Kho vận Ngoại thương...,Vận tải,Hàng & Dịch vụ Công nghiệp,"Kho bãi, hậu cần và bảo dưỡng",CT,2000,2700,2770,2777

In [21]:
list.icb_name2.unique()

<StringArray>
[                     'Hóa chất',             'Tài nguyên Cơ bản',
          'Xây dựng và Vật liệu',             'Dịch vụ tài chính',
    'Hàng & Dịch vụ Công nghiệp',                  'Truyền thông',
       'Hàng cá nhân & Gia dụng',                          'Y tế',
                  'Bất động sản',           'Du lịch và Giải trí',
          'Thực phẩm và đồ uống',                     'Ngân hàng',
 'Điện, nước & xăng dầu khí đốt',                      'Bảo hiểm',
           'Công nghệ Thông tin',                        'Bán lẻ',
              'Ô tô và phụ tùng',                       'Dầu khí',
                    'Viễn thông']
Length: 19, dtype: str

In [22]:
symbol_nh=list[list.icb_name2=='Ngân hàng'].symbol.tolist()
symbol_nh

['BID',
 'ABB',
 'EIB',
 'CTG',
 'VAB',
 'ACB',
 'SSB',
 'HDB',
 'VIB',
 'BVB',
 'NAB',
 'KLB',
 'MBB',
 'VPB',
 'PGB',
 'VBB',
 'LPB',
 'NVB',
 'BAB',
 'SGB',
 'SHB',
 'STB',
 'TCB',
 'MSB',
 'OCB',
 'TPB',
 'VCB']

In [29]:
from vnstock import Finance
finance = Finance(symbol="VCB", source="VCI")
df = finance.balance_sheet(period="year",lang='vi')
df.to_excel('VCB_BCDKT.xlsx')
df

,CP,Năm,TỔNG CỘNG TÀI SẢN (đồng),Tiền và tương đương tiền (đồng),Tiền gửi tại ngân hàng nhà nước Việt Nam,Tiền gửi tại các TCTD khác và cho vay các TCTD khác,Chứng khoán kinh doanh,_Chứng khoán kinh doanh,Dự phòng giảm giá chứng khoán kinh doanh,Các công cụ tài chính phái sinh và khoản nợ tài chính khác,...,Các khoản nợ khác,VỐN CHỦ SỞ HỮU (đồng),Vốn của tổ chức tín dụng,Quỹ của tổ chức tín dụng,Chênh lệch tỷ giá hối đoái,Chênh lệch đánh giá lại tài sản,Lãi chưa phân phối (đồng),Vốn góp của chủ sở hữu (đồng),Các quỹ khác,LỢI ÍCH CỦA CỔ ĐÔNG THIỂU SỐ
0,VCB,2025,2442279166000000,15542769000000,37445504000000,522474362000000,11832577000000,11900000000000,-67423000000,374918000000,...,36797946000000,224558726000000,89361977000000,48221262000000,-918676000000,0,87822642000000,83556751000000,809837000000,71521000000
1,VCB,2024,2085873522000000,14268064000000,49340493000000,389951898000000,4876237000000,4908527000000,-32290000000,1314434000000,...,38102621000000,196209168000000,61696139000000,37052974000000,-968292000000,0,98332086000000,55890913000000,809837000000,96261000000
2,VCB,2023,1839724560000000,14504849000000,58104503000000,336501657000000,2495408000000,2511395000000,-15987000000,0,...,43405902000000,165080490000000,61696139000000,27447116000000,-983237000000,0,76826482000000,55890913000000,809837000000,93990000000
3,VCB,2022,1813815170000000,18348534000000,92557809000000,313637444000000,1499687000000,1543575000000,-43888000000,156515000000,...,109533756000000,135646085000000,53130392000000,22556958000000,-863071000000,0,60733423000000,47325166000000,809837000000,88383000000
4,VCB,2021,1414986259000000,18011766000000,22506711000000,225811765000000,2799649000000,2856082000000,-56433000000,303202000000,...,33854570000000,109186429000000,42428821000000,18173068000000,-5109000000,0,48502536000000,37088774000000,344658000000,87113000000
5,VCB,2020,1326230092000000,15095394000000,33139373000000,267969645000000,1954061000000,1991861000000,-37800000000,0,...,33953811000000,94094979000000,42428821000000,14925803000000,5103000000,0,36650228000000,37088774000000,344658000000,85024000000
6,VCB,2019,1222813692000000,13778358000000,34684091000000,249470372000000,1801126000000,1889628000000,-88502000000,98312000000,...,26021232000000,80954337000000,42428821000000,12186141000000,16361000000,113011000000,26126544000000,37088774000000,344658000000,83459000000
7,VCB,2018,1074026560000000,12792045000000,10845701000000,250228037000000,2654806000000,2725051000000,-70245000000,275983000000,...,21221737000000,62179379000000,36322343000000,9445732000000,84450000000,119178000000,16138687000000,35977686000000,344657000000,68989000000
8,VCB,2017,1035293283000000,10102861000000,93615618000000,232973403000000,9669033000000,9750244000000,-81211000000,832354000000,...,17650679000000,52557959000000,36321931000000,7253682000000,94485000000,83285000000,8715252000000,35977686000000,344245000000,89324000000
9,VCB,2016,787935088000000,9692053000000,17382418000000,151845570000000,4233529000000,4271362000000,-37833000000,230658000000,...,12661994000000,48145556000000,36022846000000,5936667000000,84245000000,83285000000,5874992000000,35977686000000,45160000000,143521000000
10,VCB,2015,674394640000000,8519334000000,19715035000000,131527373000000,9925046000000,9941389000000,-16343000000,628000000,...,11965744000000,45172342000000,32420681000000,4941362000000,79969000000,89222000000,7475808000000,26650203000000,45160000000,165300000000
11,VCB,2014,576995651000000,8323385000000,13267101000000,146076521000000,10122143000000,10126592000000,-4449000000,0,...,11704319000000,43472763000000,32420681000000,4151991000000,67236000000,83405000000,6601598000000,26650203000000,45160000000,147852000000
12,VCB,2013,468994032000000,6059673000000,24843632000000,91737049000000,195270000000,196158000000,-888000000,136725000000,...,15532445000000,42386065000000,32420728000000,3468552000000,123853000000,82306000000,6290626000000,23174171000000,45160000000,149627000000

In [6]:
df

,CP,Năm,TÀI SẢN NGẮN HẠN (đồng),Tiền và tương đương tiền (đồng),Giá trị thuần đầu tư ngắn hạn (đồng),Các khoản phải thu ngắn hạn (đồng),Hàng tồn kho ròng,Tài sản lưu động khác,TÀI SẢN DÀI HẠN (đồng),Tài sản cố định (đồng),...,"Hàng tồn kho, ròng (đồng)",Tài sản lưu động khác (đồng),Cổ phiếu phổ thông (đồng),Vốn góp của chủ sở hữu (đồng),Vay và nợ thuê tài chính dài hạn (đồng),Người mua trả tiền trước ngắn hạn (đồng),Vay và nợ thuê tài chính ngắn hạn (đồng),Trả trước dài hạn (đồng),Tài sản dài hạn khác (đồng),LỢI ÍCH CỦA CỔ ĐÔNG THIỂU SỐ
0,VCI,2025,35868914519259,3213693581406,32122673168645,453431852403,0,79115916805,136950316556,75269933896,...,0,47532623600,8.501000e+12,8501000000000,0,16310349027,16064550000000,5432446692,0,0.000000e+00
1,VCI,2024,26491835561026,4743771932745,21072524575199,506858248065,0,168680805017,100288918214,37268698440,...,0,135374861200,7.180995e+12,7180994800000,0,2743133560,12573864000000,6238956911,0,0.000000e+00
2,VCI,2023,17174448616966,787897819240,15097165308797,1094491429414,0,194894059515,80686039559,23425609453,...,0,147257185100,4.375000e+12,4375000000000,0,378319774,8979275000000,7943878800,0,0.000000e+00
3,VCI,2022,14157693071824,3423501614803,10562264962864,120085485886,0,51841008271,85058244998,23496558588,...,0,46136989800,4.354999e+12,4354999010000,0,221000000,6326207142857,13290531600,0,0.000000e+00
4,VCI,2021,16568965942558,1131748599533,14998113044339,285206345277,0,153897953409,67299004559,13155825424,...,0,150714917648,3.330000e+12,3330000000000,0,52551076244,6362680000000,10702485700,0,0.000000e+00
5,VCI,2020,8312170798945,642512983590,6697916243107,221798617565,0,97527648804,70234326495,14384201512,...,0,91333803000,1.656000e+12,1656000000000,0,7971369863,2696130000000,12950546970,0,0.000000e+00
6,VCI,2019,7173102515011,794511762602,5817229478552,747087592357,0,165433739031,69857713462,9907318916,...,0,164204396000,1.644000e+12,1644000000000,0,210000000,1450980000000,17085900679,0,0.000000e+00
7,VCI,2018,6430493843962,1144361568890,5252959790479,30487868695,0,2684615898,79502079245,18226354386,...,0,0,1.629999e+12,1629998900000,0,126324890101,984860000000,25494063880,0,0.000000e+00
8,VCI,2017,6342806740944,486703202803,5709256554482,28256236703,0,118590746956,59205004260,25326131092,...,0,116156411000,1.200000e+12,1200000000000,0,462392057000,1434460418662,2171535344,0,0.000000e+00
9,VCI,2016,3075625891871,545670784533,2481417250820,44869461531,0,7607339062,34921874969,9489824544,...,0,1335936000,1.032000e+12,1032000000000,0,571264678998,627508000000,4433448206,0,7.721605e+10
10,VCI,2015,2423478575254,158181741192,2092718191471,78849205458,0,92517941380,39867670505,14899441202,...,0,87885991500,5.000000e+11,500000000000,0,799974087998,535500000000,9817929938,0,7.475699e+10
11,VCI,2014,2707101348631,618777857754,1939716412996,141064801745,14179400,7528096736,63219168401,18390029859,...,14179400,3095401526,5.000000e+11,500000000000,0,840646942003,266511750000,14560154043,14160000000,7.604128e+10
12,VCI,2013,2090711345801,312645301464,1659030664666,117641213076,16677400,1377489195,41576018914,11027268785,...,16677400,87777500,0.000000e+00,398400000000,0,470366997300,648400000000,16231644217,0,0.000000e+00
13,VCI,2011,1795452129469,111616718751,1059922610501,614818783909,12320284,9081696024,622201775573,7612776214,...,12320284,6609715987,3.780000e+11,378000000000,500000000000,121749992655,582426780000,0,594640525000,0.000000e+00

In [30]:
from vnstock import Finance
finance = Finance(symbol="VCB", source="VCI")
df = finance.cash_flow(period="year",lang='vi')
df.to_excel('VCB_LCTT.xlsx') 
df

,CP,Năm,(Lãi)/lỗ các hoạt động khác,Lưu chuyển tiền thuần từ HĐKD trước thay đổi VLĐ,Lưu chuyển tiền thuần từ HĐKD trước thuế,Chi từ các quỹ của TCTD,Mua sắm TSCĐ,Tiền thu cổ tức và lợi nhuận được chia,Lưu chuyển từ hoạt động đầu tư,Tăng vốn cổ phần từ góp vốn và/hoặc phát hành cổ phiếu,Lưu chuyển tiền từ hoạt động tài chính,Lưu chuyển tiền thuần trong kỳ,Tiền và tương đương tiền,Tiền và tương đương tiền cuối kỳ,Lưu chuyển tiền tệ ròng từ các hoạt động SXKD,Tiền thu được từ thanh lý tài sản cố định,Đầu tư vào các doanh nghiệp khác,Tiền thu từ việc bán các khoản đầu tư vào doanh nghiệp khác,Cổ tức đã trả
0,VCB,2025,-340404000000,38419635000000,118855603000000,-2625052000000,-1453488000000,118576000000,-1379136000000,0,-3776798000000,111074617000000,430614185000000,541688802000000,116230551000000,17231000000,-60167000000,0,-3776798000000
1,VCB,2024,-1390558000000,30183878000000,61999557000000,-2876726000000,-1480121000000,160709000000,-1307413000000,0,-19963000000,57795455000000,372818730000000,430614185000000,59122831000000,12504000000,0,747000000,-19963000000
2,VCB,2023,179388000000,43370999000000,-35738696000000,-2802834000000,-1008160000000,146088000000,-859407000000,0,-15627000000,-39416564000000,412235294000000,372818730000000,-38541530000000,9435000000,0,0,-15627000000
3,VCB,2022,-351728000000,43769595000000,185960143000000,-2538654000000,-711567000000,106555000000,-392168000000,0,-3348022000000,179681299000000,232553995000000,412235294000000,183421489000000,15753000000,0,201899000000,-3348022000000
4,VCB,2021,-526224000000,32489056000000,-53766010000000,-2786463000000,-1621433000000,93953000000,-1589936000000,0,-1886298000000,-60028707000000,292582702000000,232553995000000,-56552473000000,8456000000,-83502000000,13791000000,-1886298000000
5,VCB,2020,-628988000000,29528536000000,27469577000000,-1866142000000,-3001902000000,83959000000,-2305153000000,0,-2986115000000,20312167000000,272270535000000,292582702000000,25603435000000,10569000000,0,605274000000,-2986115000000
6,VCB,2019,-115005000000,26469418000000,26510053000000,-1434221000000,-1005065000000,197571000000,-706447000000,6106477000000,3886994000000,28256379000000,244014156000000,272270535000000,25075832000000,11589000000,0,95773000000,-2219483000000
7,VCB,2018,-42957000000,21540011000000,-58869162000000,-1365175000000,-1133639000000,129753000000,1629227000000,0,-2914981000000,-61520091000000,305534247000000,244014156000000,-60234337000000,6767000000,0,2628038000000,-2914981000000
8,VCB,2017,-90716000000,18282505000000,152747160000000,-1141469000000,-1139976000000,129685000000,-739457000000,0,-2896942000000,147969292000000,157564955000000,305534247000000,151605691000000,7542000000,0,265688000000,-2896942000000
9,VCB,2016,-209799000000,14523881000000,-1760512000000,-1199774000000,-1272248000000,31672000000,-1222592000000,0,-2665020000000,-6847898000000,164412853000000,157564955000000,-2960286000000,7206000000,0,12540000000,-2665020000000
10,VCB,2015,67753000000,11486376000000,-6240446000000,-497726000000,-1194037000000,90255000000,-1196951000000,0,-2665020000000,-10600143000000,175012996000000,164412853000000,-6738172000000,5254000000,-108464000000,12100000000,-2665020000000
11,VCB,2014,354603000000,10118084000000,42527500000000,-522245000000,-987172000000,160541000000,-1330779000000,0,-2801442000000,37873034000000,137139962000000,175012996000000,42005255000000,5900000000,-517102000000,9565000000,-2801395000000
12,VCB,2013,245971000000,8022914000000,20210304000000,-372963000000,-1170801000000,283396000000,-624325000000,0,-2780901000000,16432115000000,120707847000000,137139962000000,19837341000000,2819000000,-100347000000,362909000000,-2780901000000

In [35]:
from vnstock import Finance
finance = Finance(symbol="VCB", source="VCI")
df = finance.ratio(period="year",lang='vi')
df.to_excel('VCB_BCTC.xlsx') 
df

   Meta          Chỉ tiêu cơ cấu nguồn vốn                      \
     CP   Năm Kỳ            TSCĐ / Vốn CSH Vốn CSH/Vốn điều lệ
0   VCB  2025  5                  0.036353            2.687499
1   VCB  2024  5                  0.041246            2.348214
2   VCB  2023  5                  0.047280            1.975669
3   VCB  2022  5                  0.058869            1.623401
4   VCB  2021  5                  0.079097            1.306734
5   VCB  2020  5                  0.090753            1.126121
6   VCB  2019  5                  0.082843            0.968855
7   VCB  2018  5                  0.104978            0.744157
8   VCB  2017  5                  0.117249            0.629009
9   VCB  2016  5                  0.119007            0.576202
10  VCB  2015  5                  0.111561            0.540619
11  VCB  2014  5                  0.102697            0.520278
12  VCB  2013  5                  0.096392            0.507273

   Chỉ tiêu khả năng sinh lợi                                         \
      Biên lợi nhuận ròng (%)   ROE (%)   ROA (%) Tỷ suất cổ tức (%)
0                    0.598551  0.167303  0.015546           0.000000
1                    0.610612  0.187402  0.017247           0.007826
2                    0.617390  0.219880  0.018095           0.000000
3                    0.561521  0.244404  0.018533           0.000000
4                    0.520352  0.215922  0.016009           0.000000
5                    0.508504  0.211141  0.014494           0.015228
6                    0.538028  0.258992  0.016132           0.008122
7                    0.514127  0.254879  0.013864           0.008122
8                    0.414407  0.180939  0.009994           0.008122
9                    0.371007  0.147773  0.009430           0.008122
10                   0.343876  0.120301  0.008522           0.010152
11                   0.380264  0.106820  0.008768           0.010152
12                   0.404182  0.104311  0.009910           0.012183

   Chỉ tiêu thanh khoản Chỉ tiêu định giá                            \
      Đòn bẩy tài chính Vốn hóa (Tỷ đồng) Số CP lưu hành (Triệu CP)
0             10.875904   496327100940000                8355675100
1             10.630867   321372749750000                5589091300
2             11.144409   509725126560000                5589091300
3             13.371674   380021082980000                4732516600
4             12.959360   296710192000000                3708877400
5             14.094589   292259539120000                3708877400
6             15.104981   365324423900000                3708877400
7             17.273035   354380207100000                3597768600
8             19.698126   354380207100000                3597768600
9             16.365687   354380207100000                3597768600
10            14.929371   262504499550000                2665020300
11            13.272578   262504499550000                2665020300
12            11.064817   228265584350000                2317417100


          P/E       P/B        P/S P/Cash Flow    EPS (VND)    BVPS (VND)
0   14.109155  2.210937   6.850179    4.270195  4210.032413  26866.435364
1   10.330341  1.638713   4.686203    5.435679  6053.110279  35088.513763
2   16.748010  3.090767   7.526566  -13.225347  5922.434475  29507.243154
3   14.282450  2.803390   5.581747    2.071846  6317.783228  28643.893610
4   15.077801  2.721356   5.230810   -5.246635  5930.797551  29397.110835
5   18.187342  3.108815   5.956877   11.414857  4974.904536  25347.280285
6   22.770018  4.521369   7.988659   14.568786  5010.209828  21785.439174
7   29.542868  5.705651   9.022259   -5.883359  4059.621289  17263.586658
8   49.236501  6.754134  12.051240    2.337513  2526.863456  14583.660272
9   64.824434  7.382608  14.240224 -119.711476  1911.120965  13342.168532
10  60.254414  5.832521  12.381238  -38.957821  1993.954042  16888.067232
11  69.054727  6.058974  15.186629    6.249325  1713.500644  16256.878419
12  52.377894  5.385392  14.719828   11.506864  1880.564358  18290.218451

In [37]:
import pandas as pd
df=pd.DataFrame()
for i in symbol_nh:
    finance = Finance(symbol=i, source="VCI")
    x = finance.ratio(period="year",lang='vi')
    df=pd.concat([df,x])
df.to_excel('ratio.xlsx') 
df

   Meta          Chỉ tiêu cơ cấu nguồn vốn                      \
     CP   Năm Kỳ            TSCĐ / Vốn CSH Vốn CSH/Vốn điều lệ
0   BID  2025  5                  0.075614            2.383947
1   BID  2024  5                  0.083636            1.990519
2   BID  2023  5                  0.090310            1.687717
3   BID  2022  5                  0.101226            1.430186
4   BID  2021  5                  0.124422            1.185828
..  ...   ... ..                       ...                 ...
8   VCB  2017  5                  0.117249            0.629009
9   VCB  2016  5                  0.119007            0.576202
10  VCB  2015  5                  0.111561            0.540619
11  VCB  2014  5                  0.102697            0.520278
12  VCB  2013  5                  0.096392            0.507273

   Chỉ tiêu khả năng sinh lợi                                         \
      Biên lợi nhuận ròng (%)   ROE (%)   ROA (%) Tỷ suất cổ tức (%)
0                    0.472458  0.191106  0.009991           0.000000
1                    0.433392  0.191233  0.010117           0.011568
2                    0.383089  0.193644  0.009941           0.000000
3                    0.323195  0.193367  0.009489           0.000000
4                    0.225105  0.130637  0.006614           0.000000
..                        ...       ...       ...                ...
8                    0.414407  0.180939  0.009994           0.008122
9                    0.371007  0.147773  0.009430           0.008122
10                   0.343876  0.120301  0.008522           0.010152
11                   0.380264  0.106820  0.008768           0.010152
12                   0.404182  0.104311  0.009910           0.012183

   Chỉ tiêu thanh khoản Chỉ tiêu định giá                            \
      Đòn bẩy tài chính Vốn hóa (Tỷ đồng) Số CP lưu hành (Triệu CP)
0             19.191991      2.850673e+14              7.021362e+09
1             19.051623      2.683133e+14              6.897515e+09
2             18.726516      2.140514e+14              5.700436e+09
3             20.367914      2.195399e+14              5.058524e+09
4             20.406761      1.952590e+14              5.058524e+09
..                  ...               ...                       ...
8             19.698126      3.543802e+14              3.597769e+09
9             16.365687      3.543802e+14              3.597769e+09
10            14.929371      2.625045e+14              2.665020e+09
11            13.272578      2.625045e+14              2.665020e+09
12            11.064817      2.282656e+14              2.317417e+09


          P/E       P/B        P/S P/Cash Flow    EPS (VND)    BVPS (VND)
0    9.532664  1.696941   3.125260    1.477488  4259.040401  23925.409542
1   12.204293  1.920955   3.310023    2.714437  3644.796120  20250.346382
2   11.369013  1.815522   2.931688   -3.014172  3772.504134  20682.757787
3   14.278787  2.207145   3.155105    1.656681  3575.333903  19663.415250
4   23.060805  2.348695   3.124454    2.834354  2083.639063  16434.655572
..        ...       ...        ...         ...          ...           ...
8   49.236501  6.754134  12.051240    2.337513  2526.863456  14583.660272
9   64.824434  7.382608  14.240224 -119.711476  1911.120965  13342.168532
10  60.254414  5.832521  12.381238  -38.957821  1993.954042  16888.067232
11  69.054727  6.058974  15.186629    6.249325  1713.500644  16256.878419
12  52.377894  5.385392  14.719828   11.506864  1880.564358  18290.218451

[361 rows x 18 columns]

In [38]:
import pandas as pd
df=pd.DataFrame()
for i in symbol_nh:
    finance = Finance(symbol=i, source="VCI")
    x = finance.balance_sheet(period="year",lang='vi')
    df=pd.concat([df,x])
df.to_excel('CDKT.xlsx') 
df

,CP,Năm,TỔNG CỘNG TÀI SẢN (đồng),Tiền và tương đương tiền (đồng),Tiền gửi tại ngân hàng nhà nước Việt Nam,Tiền gửi tại các TCTD khác và cho vay các TCTD khác,Chứng khoán kinh doanh,_Chứng khoán kinh doanh,Dự phòng giảm giá chứng khoán kinh doanh,Các công cụ tài chính phái sinh và khoản nợ tài chính khác,...,VỐN CHỦ SỞ HỮU (đồng),Vốn của tổ chức tín dụng,Quỹ của tổ chức tín dụng,Chênh lệch tỷ giá hối đoái,Lãi chưa phân phối (đồng),Vốn góp của chủ sở hữu (đồng),Các quỹ khác,LỢI ÍCH CỦA CỔ ĐÔNG THIỂU SỐ,Giá trị ròng tài sản đầu tư,Chênh lệch đánh giá lại tài sản
0,BID,2025,3330825720000000,13075066000000,123629833000000,457353489000000,3.015246e+13,3.018381e+13,-3.134700e+10,0,...,173552902000000,90089431000000,33710640000000,-5.973970e+11,44786285000000,70213619000000,1.000084e+12,5.563943e+12,NaN,NaN
1,BID,2024,2760791854000000,10772890000000,92341029000000,279971515000000,1.273406e+13,1.277334e+13,-3.928000e+10,663256000000,...,144911113000000,84788796000000,19396820000000,-7.010360e+11,36192494000000,68975153000000,4.526230e+11,5.234039e+12,NaN,NaN
2,BID,2023,2300868728000000,11029204000000,51615657000000,211812201000000,6.972474e+12,7.003656e+12,-3.118200e+10,0,...,122866889000000,72711297000000,15662247000000,-8.035470e+11,30330738000000,57004359000000,3.459180e+11,4.966154e+12,NaN,NaN
3,BID,2022,2120676711000000,13745228000000,111418448000000,221177798000000,1.701464e+12,1.748521e+12,-4.705700e+10,1038214000000,...,104118505000000,66204497000000,12447663000000,-7.604040e+11,21503511000000,50585239000000,2.678510e+11,4.723238e+12,NaN,NaN
4,BID,2021,1761695792000000,12660583000000,68851444000000,135940229000000,6.068913e+12,6.083165e+12,-1.425200e+10,192282000000,...,86329026000000,65145472000000,9684951000000,-3.678820e+11,8672557000000,50585239000000,2.678510e+11,3.193928e+12,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8,VCB,2017,1035293283000000,10102861000000,93615618000000,232973403000000,9.669033e+12,9.750244e+12,-8.121100e+10,832354000000,...,52557959000000,36321931000000,7253682000000,9.448500e+10,8715252000000,35977686000000,3.442450e+11,8.932400e+10,NaN,8.328500e+10
9,VCB,2016,787935088000000,9692053000000,17382418000000,151845570000000,4.233529e+12,4.271362e+12,-3.783300e+10,230658000000,...,48145556000000,36022846000000,5936667000000,8.424500e+10,5874992000000,35977686000000,4.516000e+10,1.435210e+11,NaN,8.328500e+10
10,VCB,2015,674394640000000,8519334000000,19715035000000,131527373000000,9.925046e+12,9.941389e+12,-1.634300e+10,628000000,...,45172342000000,32420681000000,4941362000000,7.996900e+10,7475808000000,26650203000000,4.516000e+10,1.653000e+11,NaN,8.922200e+10
11,VCB,2014,576995651000000,8323385000000,13267101000000,146076521000000,1.012214e+13,1.012659e+13,-4.449000e+09,0,...,43472763000000,32420681000000,4151991000000,6.723600e+10,6601598000000,26650203000000,4.516000e+10,1.478520e+11,NaN,8.340500e+10
12,VCB,2013,468994032000000,6059673000000,24843632000000,91737049000000,1.952700e+11,1.961580e+11,-8.880000e+08,136725000000,...,42386065000000,32420728000000,3468552000000,1.238530e+11,6290626000000,23174171000000,4.516000e+10,1.496270e+11,NaN,8.230600e+10